### ISSUE TITLE
Better imdb Alfred Workflow still has error after running Alfred-fixum

### ISSUE THREAD

**Issue by innovation-counsel** [deanishe/alfred-fixum#10]
![Screen Shot 2019-12-07 at 1 32 12 pm](https://user-images.githubusercontent.com/42198015/70367672-377a3a00-18f6-11ea-9d03-c27bc058b7b0.png)

Imdb Workflow was downloaded from here:
http://www.packal.org/workflow/better-imdb-search
Last updated: 17 Dec 2014 

Can we get this workflow working in Alfred 4?

**Comment by deanishe** [comment]
I think you may have accidentally posted to the wrong repo.

That workflow has nothing to do with this one.
