### ISSUE TITLE
fixum still cannot fix the workflow

### ISSUE THREAD

**Issue by mandymilk** [deanishe/alfred-fixum#3]
I fixed the workflow but it still cannot run with alfred. and the fixum shows no workflow can be updated again.
![snip20170724_6](https://user-images.githubusercontent.com/14155391/28509759-c976534c-7076-11e7-839d-2ec2d118f70b.png)
![snip20170724_6](https://user-images.githubusercontent.com/14155391/28509765-d6364920-7076-11e7-918e-0e6993ecbf63.png)
![image](https://user-images.githubusercontent.com/14155391/28509784-e5bc4552-7076-11e7-9485-4403bb717c51.png)
[user.workflow.A345A40D-0A7D-440C-B3F6-28B39C9FCEA5.zip](https://github.com/deanishe/alfred-fixum/files/1168896/user.workflow.A345A40D-0A7D-440C-B3F6-28B39C9FCEA5.zip)

**Comment by deanishe** [comment]
Screenshots are not helpful.

Please post the contents of the log file, and if possible, a link to the workflow you posted.

**Comment by deanishe** [comment]
FWIW, your workflow appears to be invalid. Alfred refuses to install it.

In any case, it is not compatible with Alfred-Workflow, as it doesn't have a bundle ID.
