### ISSUE TITLE
Does No fix my problem

### ISSUE THREAD

**Issue by gangyou123** [deanishe/alfred-fixum#4]
I got a error in workflow for this problem. And install the fixum workflow then execute "Fix Workflows", but notified "Updated 0 workflow(s)". My workflow still can not work.

**Comment by deanishe** [comment]
That's not enough information to do anything.

Which workflow? Where's the code? What does the log file say?

**Comment by gangyou123** [comment]
But the document does not show where is the log that can get enough information. Will you please give me the log path and name ?

**Comment by deanishe** [comment]
Run the workflow.

![fixum](https://user-images.githubusercontent.com/747913/28714287-170f9c8e-7393-11e7-90e1-bfa9f43de952.png)

Which workflow isn't working? Where's the source code?

**Comment by gangyou123** [comment]
I got the answer. The workflow was written by my colleague. The "bundleid" was not assigned when the workflow was created. So "fixum" does not fix the workflow. After I give a bundleid in the place where the follow pic shows, and then run "Fix workflows", I have fix the problem. Thank you for your help @deanishe and @frdmn :)

![image](https://user-images.githubusercontent.com/30503829/28725862-6b164f9a-73f1-11e7-849d-e2e975e2279c.png)

**Comment by deanishe** [comment]
Same issue as #3 then. 

Fixum ignores workflows without a bundle ID because Alfred-Workflow also expects a bundle ID.
