### ISSUE TITLE
Is there a plan to have fixum for Alfred 2 users

### ISSUE THREAD

**Issue by dz902** [deanishe/alfred-fixum#7]
I almost always manually dismiss the hanging Python process when I hear my Mac humming, until one day I was on battery and was in a cold room...

The battery was drained silently in 1.5 hours and I have no charger...

Please consider having fixum for Alfred 2. Thank you very much!

**Comment by deanishe** [comment]
> Please consider having fixum for Alfred 2

Sorry, I'm not going to do that.

Alfred 2 was already long obsolete when the bug and the workflow were created. As the bug only occurs on Sierra and later, the only people having problems with Alfred 2 are people who could, but won't install Alfred 3.

That said, the workflow doesn't use any Alfred 3-only features, and would be very simple to remake in Alfred 2. You'd only need to recreate the Script Filter and Run Script elements, and replace the `Workflow3` class with `Workflow` in `fixum.py` to have a version that works with Alfred 2.

So if you don't want to upgrade to Alfred 3, I suggest you do that.
